# ============================================================================
# Starship Prompt Configuration
# A minimal, fast, and cross-platform prompt
# ============================================================================

# Main prompt format
format = """
$username\
$hostname\
$directory\
$python\
$nodejs\
$go\
$rust\
$zig\
$lua\
$ruby\
$character"""

right_format = "$git_branch$git_status$time"

add_newline = false

# ============================================================================
# Directory
# ============================================================================
[directory]
truncation_length = 3
truncate_to_repo = false
home_symbol = "~"
read_only = " 🔒"

# ============================================================================
# Git Configuration
# ============================================================================
[git_branch]
format = "git:$branch"
style = "bold purple"

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "red"

[python]
symbol = "Py"
format = "[$symbol]($style)"
version_format = ""
pyenv_version_name = false
style = "yellow bold"
detect_extensions = ["py"]
detect_files = [".python-version", "Pipfile", "requirements.txt", "pyproject.toml", "setup.py"]
detect_folders = []

[nodejs]
symbol = "Node"
format = "[$symbol]($style)"
detect_extensions = ["js", "mjs", "cjs", "ts", "tsx"]
detect_files = ["package.json", ".node-version", ".nvmrc"]

[golang]
symbol = "Go"
format = "[$symbol]($style)"
style = "bold cyan"

[rust]
symbol = "Rust"
format = "[$symbol]($style)"
style = "bold red"

[zig]
symbol = "Zig"
format = "[$symbol]($style)"
style = "bold yellow"

[lua]
symbol = "Lua"
format = "[$symbol]($style)"
style = "bold blue"

[ruby]
symbol = "Rb"
format = "[$symbol]($style)"
style = "bold red"
detect_extensions = ["rb"]
detect_files = ["Gemfile", ".ruby-version"]

# ============================================================================
# System Information
# ============================================================================

[username]
show_always = false
format = "[$user]($style)@"
style_user = "bold yellow"
style_root = "bold red"

[hostname]
ssh_only = true
format = "[$hostname]($style) in "
style = "bold green"
disabled = false

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
style = "dimmed white"
use_12hr = false
