[misc]
disable = ["containers", "microsoft_office", "node", "pnpm", "yarn"]
display_time = true
cleanup = true
notify_end = "never"

[brew]
greedy_cask = true
greedy_latest = true
greedy_auto_updates = true
autoremove = true

[git]
repos = ["~/Code/*/"]

[firmware]
upgrade = true
