name: Upload Docker Image On Release

on:
  workflow_dispatch:
  release:
    # Trigger when a GitHub Release is published
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.actor == github.repository_owner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Compute image tag (date)
        # Use UTC date for consistency; change +%Y-%m-%d to your preferred format
        shell: bash
        run: |
          echo "IMAGE_TAG=$(date -u +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Set REPO_NAME env
        run: echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64    # adjust/remove if you only need one
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest
